package eramo.amtalek.domain.model.auth

import com.google.gson.annotations.SerializedName

data class CompanyLoginModel(
    val actorType: String,
    val address: String,
    val attendance: Int,
    val branchId: String,
    val calls: Int,
    val ceoAcceptance: Int,
    val commission: Int,
    val companyId: Int,
    val createdAt: String,
    val dashboardLink: String,
    val deletedAt: String,
    val deptId: Int,
    val deviceToken:String,
    val doneTasks: Int,
    val email: String?,
    val hasPackage: String,
    val hrAcceptance: Int,
    val hrId: String,
    val id: Int,
    val idNumber: String?,
    val image: String?,
    val leaderId: String,
    val leads: Int,
    val meetings: Int,
    val name: String,
    val password: String,
    val phone: String,
    val prefix: String,
    val roleId: String,
    val salary: String,
    val sickVacations: Int,
    val updatedAt: String,
    val userImage: String,
    val yearlyVacations: Int,
)