package eramo.amtalek.domain.model.auth

import eramo.amtalek.data.remote.dto.bases.HasCity
import eramo.amtalek.data.remote.dto.bases.HasCountry
import eramo.amtalek.data.remote.dto.bases.HasRegion
import eramo.amtalek.data.remote.dto.drawer.myaccount.myprofile.CurrentPackageInfo


data class UserModel(
    val token:String,
    val actorType: String,
    val bio: String,
    val birthday: String,
    val city: Int,
    val cityName: String,
    val code: String,
    val codeExpiredDate: String,
    val codeSource: String,
    val codeUsage: String,
    val country: Int,
    val countryName: String,
    val createdAt: String,
    val createdFrom: String,
    val dashboardLink: String,
    val email: String,
    val emailVerifiedAt: String,
    val firebaseToken: String,
    val firstName: String,
    val gender: String?,
    val hasCity: HasCity?,
    val hasCountry: HasCountry?,
    val hasPackage: String,
    val hasRegion: HasRegion?,
    val id: Int,
    val lastName: String,
    val phone: String,
    val region: Int,
    val regionName: String,
    val status: String,
    val updatedAt: String,
    val userImage: String,
    val verified: String,
    ////////////////////////////////
    val address: String?,
    val attendance: Int?,
    val branchId: String?,
    val calls: Int?,
    val ceoAcceptance: Int?,
    val commission: Int?,
    val companyId: Int?,
    val deletedAt: String?,
    val deptId: Int?,
    val deviceToken: String?,
    val doneTasks: Int?,
    val hrAcceptance: Int?,
    val hrId: String?,
    val idNumber: String?,
    val image: String?,
    val leaderId: String?,
    val leads: Int?,
    val meetings: Int?,
    val name: String,
    val password: String?,
    val prefix: String?,
    val roleId: String?,
    val salary: String?,
    val sickVacations: Int?,
    val yearlyVacations: Int?,
    val packageInfo: CurrentPackageInfo?,
)
