package eramo.amtalek.domain.model.auth

import com.google.gson.annotations.SerializedName


data class UserModel(
//    val id: Int,
//    val token: String,
//    val firstName: String,
//    val lastName: String,
//    val phone: String,
//    val email: String,
//    val country: Int,
//    val city: Int,
//    val bio: String,
//    val profileImageUrl: String,
//    val coverImageUrl: String,
    val actorType: String,
    val bio: String,
    val token:String,
    val birthday: String,
    val city: Int,
    val cityName:String,
    val code: String,
    val codeExpiredDate: String,
    val codeSource: String,
    val codeUsage: String,
    val country: Int,
    val countryName:String,
    val createdAt: String,
    val createdFrom: String,
    val dashboardLink: String,
    val email: String,
    val emailVerifiedAt: String,
    val firebaseToken: String,
    val firstName: String,
    val gender: String,
    val hasPackage: String,
    val id: Int,
    val lastName: String,
    val phone: String,
    val region: Int,
    val status: String,
    val updatedAt: String,
    val userImage: String,
    val verified: String
)
